### ISSUE TITLE
switch k810 fn key on mac

### ISSUE THREAD

**Issue by souhaiebtar** [themech/k810_k811_fkeys#2]
i'm on mac and i'm using the k810, it's not supported out of the box, is there a way to make this script work, or at least a terminal command to switch fn keys ?

**Comment by themech** [comment]
I think it should be possible. Switching the fn keys boils down to sending [one of these sequences](https://github.com/themech/k810_k811_fkeys/blob/b5181242ed19c19cf6527a1189c899471bad8329/src/k81x.cpp#L23-L24) to your keyboard. The tricky part is how to communicate with the keyboard. The approach I took in my tool is based on Linux udev libraries and device paths and they won't work on mac. But I think one could use [this hidapi library](https://github.com/signal11/hidapi) to send one of the sequences.

**Comment by souhaiebtar** [comment]
@themech thanks for the response, i even find a program that  supposedly run on osx which is a reimplementation using hidapi instead of udev, it compile but i'm getting segmentation fault, any idea ?

**Comment by souhaiebtar** [comment]
@themech thanks, there are one projects that exist which fixed the problem, the important part is that remapping software have to be removed ( karabiner in my case)
