### ISSUE TITLE
Issue on Ubuntu 22.04

### ISSUE THREAD

**Issue by lbcd** [themech/k810_k811_fkeys#8]
Hello

I have install using : `sudo dpkg -i k81x-fkeys_0.2-1_amd64.deb`

When I launch : `sudo k81x-fkeys` I get command not found

And how can I find my device_path ?

Thank you

**Comment by themech** [comment]
Hi. This deb package installs the `k81x-fkeys` binary under `/opt/k81x/`. So `sudo /opt/k81x/k81x-fkeys` should work for you. Please let me know if it helps.

**Comment by lbcd** [comment]
Thank you @themech I found it with your indication. 
But yesterday I have used source version to install it and it works. I'm happy with this fn key inverted. 

So many thx for this share.

**Comment by themech** [comment]
Thank you @lbcd for the feedback! I'm glad the source version worked for you and you're happy with the inverted fn key functionality. Enjoy it 😄
